# https://packit.dev/docs/configuration/

specfile_path: greenboot-rs.spec

files_to_sync:
    - greenboot-rs.spec
    - .packit.yaml

upstream_package_name: greenboot-rs
downstream_package_name: greenboot-rs

upstream_tag_template: v{version}
copy_upstream_release_description: true
sync_changelog: true

# Use clean release string without commit hashes/branch names
release_suffix: ""

srpm_build_deps:
  - cargo

actions:
  get-current-version:
  - grep -oP '^Version:\s+\K\S+' greenboot-rs.spec
  create-archive:
  - "cargo vendor vendor"
  # Create archive with version for spec compatibility
  - bash -c "tar -cJf greenboot-rs-${PACKIT_PROJECT_VERSION}-vendor-patched.tar.xz vendor"
  - bash -c "git archive --prefix=greenboot-rs-${PACKIT_PROJECT_VERSION}/ --format=tar HEAD > greenboot-rs-${PACKIT_PROJECT_VERSION}.tar"
  - bash -c "tar -xvf greenboot-rs-${PACKIT_PROJECT_VERSION}.tar"
  - bash -c "tar -czf greenboot-rs-${PACKIT_PROJECT_VERSION}.tar.gz greenboot-rs-${PACKIT_PROJECT_VERSION}"
  - bash -c "rm -rf greenboot-rs-${PACKIT_PROJECT_VERSION} greenboot-rs-${PACKIT_PROJECT_VERSION}.tar vendor"
  - bash -c "ls -1 ./greenboot-rs-*.tar.gz"
  post-upstream-clone:
  - "sed -i '/^%global forgeurl/d' greenboot-rs.spec"
  - "sed -i '/^%forgemeta/d' greenboot-rs.spec"
  - "sed -i '/^%forgeautosetup/d' greenboot-rs.spec"
  - bash -c "git config user.name 'Packit Build' || true"
  - bash -c "git config user.email 'packit@fedoraproject.org' || true"
  fix-spec-file:
  # This runs after Packit's release processing - disable debug package to prevent saypaul error
  - "sed -i '/^License:/a\\%global debug_package %{nil}' greenboot-rs.spec"

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - centos-stream-10-aarch64
  - centos-stream-10-x86_64
  - fedora-development-aarch64
  - fedora-development
  - fedora-eln-aarch64
  - fedora-eln
  

